stages:
  - build
build:
  image: node:latest    # Run the job in a `node` docker image
  stage: build
  script:
    - npm install      # Run `yarn install` and `yarn build`
    - npm build
  artifacts:
    paths:
      - build/          # Save the build result as an artfact